### ISSUE TITLE
Fix CSS issue on workshop home page

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/single-spa-foundry-worker#32]

**Comment by joeldenning** [comment]
Notice how there is a blue gap between the circles and the peach horizontal rule. There shouldn't be. When you go to fix it, you'll realize the css is a bit of a disaster. Don't judge my css too harshly :) 

![image](https://user-images.githubusercontent.com/5524384/163002733-ced54a31-36a3-4cab-bcec-46f853dc5107.png)

**Comment by leahjlou** [comment]
@joeldenning which browser are you using? I noticed that in Chrome it looks right, but in Firefox there's a gap (although the gap I'm seeing is smaller than the one in your screenshot)
