### ISSUE TITLE
Foundry 1b vi - Gzipping

### ISSUE THREAD

**Issue by joeldenning** [JustUtahCoders/single-spa-foundry-worker#8]

**Comment by joeldenning** [comment]
The import map and all static files we serve should be gzipped. My understanding, reading [this discussion](https://community.cloudflare.com/t/return-compressed-response-from-worker/154117/3) is that Cloudflare will auto-compress the file on its own if we specify `content-encoding` http response header in our response.

In other words, by us pretending the file is gzipped, Cloudflare will actually make it become gzipped.

I think that gzip is the appropriate algorithm to use for the import map (rather than brotli), since the import map is being compressed "on-the-fly" rather than before hand. We're assembling the JSON in code, so the gzip has to happen right in the moment. The brotli algorithm is generally better at creating smaller files, but it's also a lot slower than gzip and so the extra time it takes to do the compression isn't worth the benefit of sending fewer bytes over the internet.

**Comment by joeldenning** [comment]
Turns out cloudflare auto compresses everything (except import maps due to content-type header). See https://support.cloudflare.com/hc/en-us/articles/200168396-What-will-Cloudflare-compress-

**Comment by Qirhi** [comment]
It was determined that Cloudflare automatically uses brotli.  Decided to go with Cloudflare default for compression of files.
